### ISSUE TITLE
SEGBugsnagIntegrationFactory is integrated as SEGCrittercismIntegrationFactory

### ISSUE THREAD

**Issue by ryanio** [segment-integrations/analytics-ios-integration-bugsnag#1]
https://github.com/segment-integrations/analytics-ios-integration-bugsnag/blob/master/Pod/Classes/SEGBugsnagIntegrationFactory.h#L5

https://github.com/segment-integrations/analytics-ios-integration-bugsnag/blob/master/Pod/Classes/SEGBugsnagIntegrationFactory.m#L5

**Comment by f2prateek** [comment]
Thanks, closed by https://github.com/segment-integrations/analytics-ios-integration-bugsnag/commit/3edb0a33f9a1508cc2c0e9a1592cdde420cde207
