### ISSUE TITLE
Support for Segment ~>3.0

### ISSUE THREAD

**Issue by dmorrow** [segment-integrations/analytics-ios-integration-bugsnag#2]
Currently the podspec has dependencies on Analytics `~> 3.0.2-alpha`.
Analytics is now at version 3.5.0.
Can this be updated?

**Comment by f2prateek** [comment]
This is fixed on master (https://github.com/segment-integrations/analytics-ios-integration-bugsnag/commit/974c0b70982035f0ef2868f4ca0ec922a7aa6828 you can use that for now) but I'll cut a release as well.

**Comment by f2prateek** [comment]
Released in 1.0.2
